name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn package

      - name: Zip application
        run: zip -r application.zip target/*.jar Dockerfile .ebextensions/

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy to EB
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name moj-projekt \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-123456789",S3Key="application.zip"
          aws elasticbeanstalk update-environment \
            --environment-name moj-projekt-env \
            --version-label ${{ github.sha }}